<?php
/**
 * Bemazal functions and definitions.
 *
 * This file contains the core logic necessary to integrate Vite with WordPress.  It conditionally
 * loads assets from the development server when `VITE_FORCE_DEV` is defined in your `wp-config.php` or
 * falls back to the compiled assets in the `dist` directory for production.  The manifest file
 * generated by Vite is used to determine the correct filenames.
 *
 * In addition to asset loading, this file sets up a few sensible defaults such as theme support for
 * document title tags and post thumbnails.
 */

if ( ! defined( 'BEMAZAL_VERSION' ) ) {
    // Version constant used for cache busting.  In production it will be replaced by the hashed file names.
    define( 'BEMAZAL_VERSION', '1.0.0' );
}





/**
 * Register theme supports and navigation menus.
 */
function bemazal_setup() {
    // Let WordPress manage the document title.
    add_theme_support( 'title-tag' );

    // Enable featured images on posts and pages.
    add_theme_support( 'post-thumbnails' );

    // Register a primary navigation location.
    register_nav_menus( [
        'primary' => __( 'Primary Menu', 'bemazal' ),
    ] );
}
add_action( 'after_setup_theme', 'bemazal_setup' );

/**
 * Determine whether to use the Vite development server.
 *
 * The Vite dev server will be used if the `VITE_FORCE_DEV` constant is defined and truthy in your
 * `wp-config.php`.  You can also define `VITE_SERVER` to override the default dev server URL.
 *
 * @return bool
 */
function bemazal_is_dev() {
    return defined( 'VITE_FORCE_DEV' ) && VITE_FORCE_DEV;
}

/**
 * Get the URL of the Vite dev server.
 *
 * @return string
 */
function bemazal_get_vite_server() {
    if ( defined( 'VITE_SERVER' ) && VITE_SERVER ) {
        return rtrim( VITE_SERVER, '/' );
    }
    // Default to bemazal.local with HTTPS if not defined.
    return 'https://bemazal.local:5173';
}

/**
 * Enqueue scripts and styles.
 *
 * In development mode the Vite client and main entry will be loaded directly from the dev server.  In
 * production the built files are looked up from the `manifest.json` generated by Vite.  The
 * `manifest.json` file must be placed in the `dist` folder.  If the manifest or assets are missing,
 * nothing will be enqueued.
 */
function bemazal_enqueue_assets() {
    $theme_uri      = get_template_directory_uri();
    $theme_dir      = get_template_directory();
    $dist_path      = $theme_dir . '/dist';
    $dist_uri       = $theme_uri . '/dist';

    // Always provide the main handle for dependencies.
    $handle = 'bemazal-main';

    if ( bemazal_is_dev() ) {
        // Development: load from Vite server.
        $vite_server = bemazal_get_vite_server();
        // Vite injects the HMR client with this endpoint.
        wp_enqueue_script( 'vite-client', $vite_server . '/@vite/client', [], null, true );
        // Main entry for our app.  Because we set `input` in `vite.config.js` this will be at /src/js/main.js
        wp_enqueue_script( $handle, $vite_server . '/src/js/main.js', [], null, true );
        return;
    }

    // Production: load manifest if it exists.
    $manifest_path = $dist_path . '/manifest.json';
    if ( ! file_exists( $manifest_path ) ) {
        // Nothing to enqueue.
        return;
    }
    $manifest = json_decode( file_get_contents( $manifest_path ), true );
    if ( ! isset( $manifest['src/js/main.js'] ) ) {
        return;
    }
    $entry = $manifest['src/js/main.js'];
    // Enqueue the JS file.
    if ( isset( $entry['file'] ) ) {
        wp_enqueue_script( $handle, $dist_uri . '/' . $entry['file'], [], BEMAZAL_VERSION, true );
    }
    // Enqueue any CSS generated for this entry.
    if ( isset( $entry['css'] ) && is_array( $entry['css'] ) ) {
        foreach ( $entry['css'] as $css_file ) {
            wp_enqueue_style( 'bemazal-style', $dist_uri . '/' . $css_file, [], BEMAZAL_VERSION );
        }
    }
}
add_action( 'wp_enqueue_scripts', 'bemazal_enqueue_assets' );

/**
 * Add type="module" attribute to Vite scripts.
 *
 * This filter modifies the script tag HTML to include the type="module" attribute
 * which is required for ES6 module syntax (import/export statements).
 *
 * @param string $tag    The script tag HTML.
 * @param string $handle The script handle.
 * @param string $src    The script source URL.
 * @return string Modified script tag.
 */
function bemazal_add_type_module( $tag, $handle, $src ) {
    // Add type="module" to Vite-related scripts
    if ( in_array( $handle, [ 'vite-client', 'bemazal-main' ], true ) ) {
        // Remove existing type attribute and add type="module"
        $tag = preg_replace( '/\stype=["\'][^"\']*["\']/', '', $tag );
        $tag = str_replace( '<script ', '<script type="module" ', $tag );
    }
    return $tag;
}
add_filter( 'script_loader_tag', 'bemazal_add_type_module', 10, 3 );

/**
 * Add no-cache headers in dev mode.
 */
function bemazal_nocache_headers() {
    if ( bemazal_is_dev() ) {
        header( 'Cache-Control: no-cache, no-store, must-revalidate' );
        header( 'Pragma: no-cache' );
        header( 'Expires: 0' );
    }
}
add_action( 'send_headers', 'bemazal_nocache_headers' );

/**
 * Disable the admin bar on the front end for a cleaner look when developing.
 */
add_filter( 'show_admin_bar', '__return_false' );